DEFAULT_MODERN_BASE_COLOR = "#292929"
DEFAULT_MODERN_ACCENT_COLOR = "#569eff"

DEFAULT_CLASSIC_BASE_COLOR = "#363d4a"
DEFAULT_CLASSIC_ACCENT_COLOR = "#70bafa"


def hex_to_rgb(hex_str):
    hex_str = hex_str.lstrip('#')
    return tuple(int(hex_str[i:i+2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return '#{:02x}{:02x}{:02x}'.format(
        max(0, min(255, int(rgb[0]))),
        max(0, min(255, int(rgb[1]))),
        max(0, min(255, int(rgb[2]))))


def darkened(hex_str, amount):
    r, g, b = hex_to_rgb(hex_str)
    f = 1.0 - amount

    return rgb_to_hex((r * f, g * f, b * f))


def lightened(hex_str, amount):
    r, g, b = hex_to_rgb(hex_str)

    return rgb_to_hex((
        r + (255 - r) * amount,
        g + (255 - g) * amount,
        b + (255 - b) * amount))


def lerp_color(c1_hex, c2_hex, t):
    r1, g1, b1 = hex_to_rgb(c1_hex)
    r2, g2, b2 = hex_to_rgb(c2_hex)

    r = r1 + (r2 - r1) * t
    g = g1 + (g2 - g1) * t
    b = b1 + (b2 - b1) * t

    return rgb_to_hex((r, g, b))


def main():
    print("--- Godot Theme Generator for Alacritty ---")

    # Getting User Input
    is_modern = input("Do you want to use the modern 4.6+ theme? (Yes, No): ").strip().lower() not in ["n", "no"]
    
    default_base_color = DEFAULT_MODERN_BASE_COLOR if is_modern else DEFAULT_CLASSIC_BASE_COLOR
    base_color_in = input(f"Enter base color [default: {default_base_color}]: ").strip()
    base_color = base_color_in if base_color_in else default_base_color

    default_accent_color = DEFAULT_MODERN_ACCENT_COLOR if is_modern else DEFAULT_CLASSIC_ACCENT_COLOR
    accent_color_in = input(f"Enter accent color [default: {default_accent_color}]: ").strip()
    accent_color = accent_color_in if accent_color_in else default_accent_color

    contrast_in = input("Enter contrast [default: 0.3]: ").strip()
    try: contrast = float(contrast_in) if contrast_in else 0.3
    except ValueError:
        print("Invalid contrast number, using 0.3")
        contrast = 0.3

    font_size_in = input("Enter font size [default: 17]: ").strip()
    try: font_size = int(font_size_in) if font_size_in else 17
    except ValueError:
        print("Invalid font size, using 17")
        font_size = 17

    font_family_in = input("Enter Accent Color [default: hack]: ").strip()
    font_family = font_family_in if font_family_in else "hack"

    font_style_in = input("Enter font style [default: Medium]: ").strip()
    font_style = font_style_in if font_style_in else "Medium"

    # Logic Translation (Same stuff which happens in Godot's EditorThemeManager.cpp)
    font_color = "#e0e0e0"

    background_color = darkened(base_color, contrast)
    background_selection = lerp_color(accent_color, base_color, 0.4)

    symbol_color = "#abc9ff"
    keyword_color = "#ff7085"
    control_flow_color = "#ff8ccc"
    base_type_color = "#42ffc2"
    engine_type_color = "#8fffdb"
    user_type_color = "#c7ffed"
    string_color = "#ffeda1"
    function_call_color = "#57b3ff"
    gd_annotation_color = "#ffb373"
    error_color = "#ff6666"
    mono_color = "#ffffff"

    # Map Godot colors to terminal colors
    black_normal = darkened(background_color, 0.2)
    black_bright = lightened(background_color, 0.3)
    red_normal = keyword_color
    red_bright = error_color
    green_normal = base_type_color
    green_bright = engine_type_color
    yellow_normal = string_color
    yellow_bright = gd_annotation_color
    blue_normal = function_call_color
    blue_bright = symbol_color
    magenta_normal = control_flow_color
    magenta_bright = control_flow_color
    cyan_normal = engine_type_color
    cyan_bright = user_type_color
    white_normal = font_color
    white_bright = mono_color

    # Generate TOML Content
    toml_content = f"""# Generated by Godot Theme Script - https://github.com/voylin/godot_color_theme
# Base: {base_color} | Accent: {accent_color} | Contrast: {contrast}
# Using Neovim Lua color generation logic

[colors.primary]
background = "{background_color}"
foreground = "{font_color}"

[colors.cursor]
text = "{background_color}"
cursor = "{mono_color}"

[colors.selection]
text = "{font_color}"
background = "{background_selection}"

# Normal colors
[colors.normal]
black   = "{black_normal}"
red     = "{red_normal}"
green   = "{green_normal}"
yellow  = "{yellow_normal}"
blue    = "{blue_normal}"
magenta = "{magenta_normal}"
cyan    = "{cyan_normal}"
white   = "{white_normal}"

# Bright colors
[colors.bright]
black   = "{black_bright}"
red     = "{red_bright}"
green   = "{green_bright}"
yellow  = "{yellow_bright}"
blue    = "{blue_bright}"
magenta = "{magenta_bright}"
cyan    = "{cyan_bright}"
white   = "{white_bright}"

[env]
TERM = "xterm-256color"

[font]
size = {font_size}

[font.normal]
family = "{font_family}"
style = "{font_style}"
"""

    filename = "alacritty.toml"
    try:
        with open(filename, "w") as f: 
            f.write(toml_content)
        print(f"\nSuccess! Created '{filename}'.")
    except IOError as e:
        print(f"Error writing file: {e}")


if __name__ == "__main__":
    main()
