import sys

DEFAULT_MODERN_BASE_COLOR = "#292929"
DEFAULT_MODERN_ACCENT_COLOR = "#569eff"

DEFAULT_CLASSIC_BASE_COLOR = "#363d4a"
DEFAULT_CLASSIC_ACCENT_COLOR = "#70bafa"


def hex_to_rgb(hex_str):
    hex_str = hex_str.lstrip('#')
    return tuple(int(hex_str[i:i+2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return '#{:02x}{:02x}{:02x}'.format(
        max(0, min(255, int(rgb[0]))),
        max(0, min(255, int(rgb[1]))),
        max(0, min(255, int(rgb[2]))))


def lerp_color(c1_hex, c2_hex, t):
    r1, g1, b1 = hex_to_rgb(c1_hex)
    r2, g2, b2 = hex_to_rgb(c2_hex)

    r = r1 + (r2 - r1) * t
    g = g1 + (g2 - g1) * t
    b = b1 + (b2 - b1) * t

    return rgb_to_hex((r, g, b))


## Simulates putting an alpha color on top of a background
def blend_color(fg_hex, bg_hex, alpha):
    return lerp_color(bg_hex, fg_hex, alpha)


def main():
    print("--- Godot Theme Generator for Alacritty ---")

    # Getting User Input
    is_modern = input("Do you want to use the modern 4.6+ theme? (Yes, No): ").strip().lower() not in ["n", "no"]
    
    default_base_color = DEFAULT_MODERN_BASE_COLOR if is_modern else DEFAULT_CLASSIC_BASE_COLOR
    base_color_in = input(f"Enter base color [default: {default_base_color}]: ").strip()
    base_color = base_color_in if base_color_in else default_base_color

    default_accent_color = DEFAULT_MODERN_ACCENT_COLOR if is_modern else DEFAULT_CLASSIC_ACCENT_COLOR
    accent_color_in = input(f"Enter accent color [default: {default_accent_color}]: ").strip()
    accent_color = accent_color_in if accent_color_in else default_accent_color

    contrast_in = input("Enter contrast [default: 0.3]: ").strip()
    try: contrast = float(contrast_in) if contrast_in else 0.3
    except ValueError:
        print("Invalid contrast number, using 0.3")
        contrast = 0.3

    font_size_in = input("Enter font size [default: 17]: ").strip()
    try: font_size = int(font_size_in) if font_size_in else 17
    except ValueError:
        print("Invalid font size, using 17")
        contrast = 17

    font_family_in = input("Enter Accent Color [default: hack]: ").strip()
    font_family = font_family_in if font_family_in else "hack"

    font_style_in = input("Enter font style [default: Medium]: ").strip()
    font_style = font_style_in if font_style_in else "Medium"

    # Logic Translation (Same stuff which happens in Godot's EditorThemeManager.cpp)
    font_color = "#e0e0e0"
    mono_color = "#ffffff"
    error_color = "#ff6666"

    bg_color = lerp_color(base_color, "#000000", contrast * 1.2)
    selection_bg = blend_color(accent_color, bg_color, 0.4)
    black_normal = blend_color("#000000", bg_color, 0.5) # Dim background
    black_bright = blend_color("#000000", bg_color, 0.7) # Lighter background
    red_normal = "#ff7085"
    red_bright = error_color
    green_normal = "#42ffc2"
    green_bright = "#63c259"
    yellow_normal = "#ffeda1"
    yellow_bright = "#ffb373"
    blue_normal = "#57b3ff"
    blue_bright = lerp_color("#57b3ff", mono_color, 0.6)
    magenta_normal = "#ff8ccc"
    magenta_bright = "#ff8ccc"
    cyan_normal = "#8fffdb"
    cyan_bright = "#c7ffed"
    white_normal = font_color
    white_bright = mono_color

    # Generate TOML Content
    toml_content = f"""# Generated by Godot Theme Script - https://github.com/voylin/godot_color_theme
# Base: {base_color} | Accent: {accent_color} | Contrast: {contrast}

[colors.primary]
background = "{bg_color}"
foreground = "{font_color}"

[colors.cursor]
text = "{bg_color}"
cursor = "{mono_color}"

[colors.selection]
text = "{font_color}"
background = "{selection_bg}"

# Normal colors
[colors.normal]
black   = "{black_normal}"
red     = "{red_normal}"
green   = "{green_normal}"
yellow  = "{yellow_normal}"
blue    = "{blue_normal}"
magenta = "{magenta_normal}"
cyan    = "{cyan_normal}"
white   = "{white_normal}"

# Bright colors
[colors.bright]
black   = "{black_bright}"
red     = "{red_bright}"
green   = "{green_bright}"
yellow  = "{yellow_bright}"
blue    = "{blue_bright}"
magenta = "{magenta_bright}"
cyan    = "{cyan_bright}"
white   = "{white_bright}"

[env]
TERM = "xterm-256color"

[font]
size = {font_size}

[font.normal]
family = "{font_family}"
style = "{font_style}"
"""

    filename = "alacritty.toml"
    try:
        with open(filename, "w") as f: f.write(toml_content)
        print(f"\nSuccess! Created '{filename}'.")
        print(f"Background calculated as: {bg_color}")
    except IOError as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    main()
